Generate tendermint types
figment-networks/graph-ts pull request #1
Opened 2021-10-26 18:13 UTC by patiee

Tendermint typescript types

2021-12-17 15:42 UTC, pienkowb requested changes
I've added a few comments. The rest of the code looks good 👍

2021-12-17 15:42 UTC, pienkowb commented on .gitignore
> +package-lock.json
It looks like Yarn is used instead of NPM for this repository. I suggest we bring back the original `.gitignore` file and keep this change locally.

2021-12-17 15:42 UTC, pienkowb commented on chain/near.ts
> -      return false
Unless this causes compilation errors I would keep the NEAR code intact.

2021-12-17 15:42 UTC, pienkowb commented on chain/near.ts
> -      return false
Same here.

2022-01-05 12:22 UTC, lavabyrd commented on global/global.ts
> +TendermintEventData = 130,
these need to be tabbed/spaced in to match those above

2022-01-07 16:02 UTC, patiee commented on chain/near.ts
> -      return false
sorry, i deleted it because of the tool

2022-01-10 12:44 UTC, pienkowb reviewed
I've left a few comments about formatting.

2022-01-10 12:44 UTC, pienkowb commented on global/global.ts
> +TendermintEventData = 130,
Looks like the indentation here still needs to be fixed.

2022-01-10 12:44 UTC, pienkowb commented on chain/tendermint.ts
> +	}
We should use the same formatting as in other files in this repository (indent with 2 spaces).

2022-01-10 12:44 UTC, pienkowb commented on chain/tendermint.ts
> +export namespace tendermint {
Minor detail: It's good to separate imports from the rest of the code with an empty line.

2022-01-10 14:54 UTC, pienkowb approved these changes
LGTM 👍

2022-01-10 14:58 UTC, lavabyrd approved these changes
looks much better to me. 👍🏻

2022-01-10 15:02 UTC, merged