Add cosmos transaction definitions
figment-networks/graph-ts pull request #5
Opened 2022-02-01 08:21 UTC by patiee

2022-02-15 14:08 UTC, jason-c-child commented
This PR was opened 14 days ago. I do not see any comments or activity (review or otherwise). It looks like there's a merge conflict rn.

2022-02-15 19:12 UTC, pienkowb commented
@jason-c-child This is a part of Cosmos transaction decoding which is still WIP.

2022-03-09 10:06 UTC, patiee commented
Do we want to keep all Tendermint-like networks under one directory or leave it under `chain`?

2022-03-17 18:54 UTC, pienkowb commented on chain/tendermint/cosmos.ts
> +    }
Are these methods generated too or did you add them manually?

2022-03-18 10:53 UTC, lavabyrd commented on chain/tendermint/tendermint.ts
> +    public block: EventBlock
The current main/master already has this fix, rebase? https://github.com/graphprotocol/graph-ts/blob/main/chain/tendermint.ts#L20

2022-03-18 12:18 UTC, patiee commented on chain/tendermint/cosmos.ts
> +    }
these methods are generated, I showed you the script yesterday. It's in closed PR in graph-proto-as-schema

2022-03-18 12:18 UTC, patiee commented on chain/tendermint/tendermint.ts
> +    public block: EventBlock
oh yes, need to merge main branch.

2022-03-23 16:56 UTC, lavabyrd commented on yarn.lock
> +  resolved "https://registry.npmjs.org/assemblyscript/-/assemblyscript-0.19.10.tgz"
any idea why these switched to npmjs instead of yarnpkg? Can we switch them back?

2022-03-23 16:58 UTC, lavabyrd requested changes
just the one point on the lock file.

Otherwise my thinking is I'd rather we have a "highlevel" tendermint.ts file that imports each chain specific piece as required

so 
chain
  tendermint.ts
  tendermint_chains/
    cosmos.ts
    terra.ts

etc we could always look at this later though, its not a show stopper for me.

2022-03-23 19:31 UTC, patiee commented on yarn.lock
> +  resolved "https://registry.npmjs.org/assemblyscript/-/assemblyscript-0.19.10.tgz"
oh good catch thanks, it's probably because I removed and regenerated that file.

2022-03-23 19:34 UTC, patiee commented
> just the one point on the lock file.
> 
> Otherwise my thinking is I'd rather we have a "highlevel" tendermint.ts file that imports each chain specific piece as required
> 
> so chain tendermint.ts tendermint_chains/ cosmos.ts terra.ts
> 
> etc we could always look at this later though, its not a show stopper for me.

Thanks Mark for comments,
I will leave Tendermint definitions inside `chain` directory and network-related definitions will be under `tendermint`.

2022-03-24 02:30 UTC, sosedoff commented
Let's rebase from main (just did upstream sync). 
As for merging - i've tried running scripts (yarn lint/build/test) and some of them are failing, probably need some small tweaks. 
LGTM if we dont need any more changes.

2022-03-24 16:07 UTC, lavabyrd commented on package.json
> +  "version": "0.26.0",
are we meant to have updated this?

2022-03-24 16:09 UTC, lavabyrd commented
also, the package lock.json file is being added. is there a reason we're using that now instead of just the lock file?

2022-03-24 16:09 UTC, lavabyrd approved these changes

2022-03-25 10:23 UTC, merged